site_name: تفکر پایتونی
theme: material

nav:
- 'index.md'
- 'chapter-01.md'
- 'chapter-02.md'
- 'chapter-03.md'
- 'chapter-04.md'
- 'chapter-05.md'
- 'chapter-06.md'
- 'chapter-07.md'
- 'chapter-08.md'
- 'chapter-09.md'
- 'chapter-10.md'
- 'chapter-11.md'
- 'chapter-12.md'
- 'chapter-13.md'
- 'chapter-14.md'
- 'chapter-15.md'
- 'chapter-16.md'
- 'chapter-17.md'
- 'chapter-18.md'
- 'chapter-19.md'
